//! Building the component-marker → trait-names map from the compiler.
//!
//! A CGP component marker (e.g. `AreaCalculatorComponent`) is an empty struct that carries
//! no link back to the consumer trait (`CanCalculateArea`) or provider trait
//! (`AreaCalculator`) it stands for. The only type-level links run the other way, and this
//! module inverts them by querying the trait solver, so [`crate::rewrite`] can name the
//! traits behind a marker that appears in a diagnostic. It is the compiler-coupled half of
//! the transform; the string rewriting it feeds is compiler-free.
//!
//! Two forward links are inverted, both generated by `#[cgp_component]`:
//!
//! - **Provider trait → marker.** Every provider trait carries `IsProviderFor<Marker, …>`
//!   as a supertrait, so scanning each trait's super-predicates for an `IsProviderFor`
//!   bound yields the (provider trait, marker) pairs.
//! - **Consumer trait → provider trait.** The consumer trait's blanket impl reads
//!   `impl<C> Consumer for C where C: Provider<C>`, so a blanket impl whose `where` clause
//!   bounds its own context on a known provider trait names that provider's consumer.
//!
//! Composing the two gives, per marker, the consumer and provider trait names.

use std::collections::HashMap;

use rustc_middle::ty::{self, TyCtxt};
use rustc_span::def_id::DefId;

use crate::rewrite::ComponentTraitNames;

/// Build the map from component-marker name to the consumer/provider trait names behind it,
/// by inverting the `IsProviderFor` supertrait and consumer-blanket-impl links across every
/// trait in scope. Returns an empty map if CGP's `IsProviderFor` trait is not in scope,
/// which is the case for a compilation that does not use CGP.
pub fn build_component_name_map(tcx: TyCtxt<'_>) -> HashMap<String, ComponentTraitNames> {
    let all_traits: Vec<DefId> = tcx.all_traits_including_private().collect();

    let Some(is_provider_for) = all_traits
        .iter()
        .copied()
        .find(|&did| tcx.item_name(did).as_str() == "IsProviderFor")
    else {
        return HashMap::new();
    };

    // Provider trait DefId → (component marker name, provider trait name), found by the
    // `IsProviderFor<Marker, …>` supertrait every provider trait carries.
    let mut providers: HashMap<DefId, (String, String)> = HashMap::new();
    for &trait_did in &all_traits {
        for &(clause, _) in tcx.explicit_super_predicates_of(trait_did).skip_binder() {
            let Some(predicate) = clause.as_trait_clause() else {
                continue;
            };
            let trait_ref = predicate.skip_binder().trait_ref;
            if trait_ref.def_id != is_provider_for {
                continue;
            }
            // Args are `[Self, Marker, Context, Params]`; the marker is the second.
            let Some(marker_ty) = trait_ref.args.get(1).copied().and_then(|arg| arg.as_type())
            else {
                continue;
            };
            if let ty::Adt(marker, _) = marker_ty.kind() {
                providers.insert(
                    trait_did,
                    (
                        tcx.item_name(marker.did()).to_string(),
                        tcx.item_name(trait_did).to_string(),
                    ),
                );
            }
        }
    }

    // Provider trait DefId → consumer trait name, found by the consumer's blanket impl
    // `impl<C> Consumer for C where C: Provider<C>`: a blanket impl bounding its *own* self
    // type on a known provider trait belongs to that provider's consumer. Requiring the
    // bound's self type to be the impl's self type is what tells this apart from the
    // provider blanket impl, which also bounds the same provider trait but on a projected
    // `<C as DelegateComponent<…>>::Delegate` rather than on `C` itself.
    let mut consumers: HashMap<DefId, String> = HashMap::new();
    for &consumer_did in &all_traits {
        for &impl_did in tcx.trait_impls_of(consumer_did).blanket_impls() {
            let impl_self_ty = tcx.type_of(impl_did).skip_binder();
            for &(clause, _) in tcx.predicates_of(impl_did).predicates {
                let Some(predicate) = clause.as_trait_clause() else {
                    continue;
                };
                let trait_ref = predicate.skip_binder().trait_ref;
                if providers.contains_key(&trait_ref.def_id) && trait_ref.self_ty() == impl_self_ty
                {
                    consumers.insert(trait_ref.def_id, tcx.item_name(consumer_did).to_string());
                }
            }
        }
    }

    providers
        .into_iter()
        .map(|(provider_did, (component, provider))| {
            // Fall back to the provider trait name if no consumer blanket impl is found, so
            // a partially-recognized component still improves the provider-side note.
            let consumer = consumers
                .get(&provider_did)
                .cloned()
                .unwrap_or_else(|| provider.clone());
            (component, ComponentTraitNames { consumer, provider })
        })
        .collect()
}
